#!/usr/bin/env node
/**
 * A fake `codex app-server` that speaks the real JSON-RPC protocol.
 *
 * Shapes match codex-cli 0.153.4 as generated by `codex app-server generate-ts`:
 * newline-delimited JSON-RPC, `thread/start` returning `result.thread.id`,
 * `turn/start` returning `result.turn.id` and streaming `item/*` notifications
 * until `turn/completed`, `turn/steer` gated on `expectedTurnId`, and server
 * requests that the client MUST answer.
 */

import * as readline from "node:readline";
import { randomUUID } from "node:crypto";

const argv = process.argv.slice(2);
if (argv.includes("--version")) {
  process.stdout.write("codex-cli 9.9.9\n");
  process.exit(0);
}
if (argv[0] === "login" && argv[1] === "status") {
  process.stdout.write("Logged in using ChatGPT\n");
  process.exit(0);
}

const emit = (obj) => process.stdout.write(`${JSON.stringify(obj)}\n`);
const notify = (method, params) => emit({ method, params });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

let threadId;
let turnId;
let interrupted = false;
let steerText;
const memory = [];
let resumed = false;

async function runTurn(text, activeTurnId) {
  // The turn id was already handed to the client by `turn/start`; minting a new
  // one here would break the `expectedTurnId` precondition on `turn/steer`.
  turnId = activeTurnId;
  interrupted = false;
  steerText = undefined;
  memory.push(text);
  notify("turn/started", { threadId, turn: { id: turnId, status: "running" } });

  if (text.includes("APPROVAL")) {
    // A server request the client must answer; the worker is stuck until it does.
    emit({
      id: 9001,
      method: "item/commandExecution/requestApproval",
      params: { kind: "command", threadId, turnId, itemId: "it-1", startedAtMs: Date.now(), reason: "needs approval" },
    });
    return; // completion happens once the approval arrives
  }

  if (text.includes("SLOW")) {
    notify("item/started", {
      threadId,
      turnId,
      item: { type: "commandExecution", id: "it-2", command: "sleep 30", cwd: process.cwd() },
    });
    for (let i = 0; i < 60; i += 1) {
      if (interrupted || steerText !== undefined) break;
      await sleep(200);
    }
    notify("item/completed", {
      threadId,
      turnId,
      item: { type: "commandExecution", id: "it-2", command: "sleep 30", exitCode: 0, durationMs: 1, aggregatedOutput: "slept" },
    });
    if (interrupted) {
      notify("turn/completed", { threadId, turn: { id: turnId, status: "interrupted" } });
      turnId = undefined;
      return;
    }
    if (steerText !== undefined) {
      memory.push(steerText);
      const answer = steerText.includes("STOP") ? "STEERED" : "CONTINUED";
      notify("item/completed", { threadId, turnId, item: { type: "agentMessage", id: "am", text: answer } });
      notify("turn/completed", { threadId, turn: { id: turnId, status: "completed" } });
      turnId = undefined;
      return;
    }
  }

  if (text.includes("WRITE")) {
    notify("item/completed", {
      threadId,
      turnId,
      item: { type: "fileChange", id: "fc", status: "completed", changes: [{ path: "NOTE.md" }] },
    });
  }

  const answer = text.includes("RECALL")
    ? memory.filter((m) => m.startsWith("REMEMBER ")).map((m) => m.slice(9)).join(",") ||
      (resumed ? "RESUMED-NO-MEMORY" : "NOTHING")
    : text.includes("REMEMBER ")
      ? "OK"
      : `echo:${text.slice(0, 40)}`;

  notify("item/completed", { threadId, turnId, item: { type: "agentMessage", id: "am", text: answer } });
  notify("turn/completed", { threadId, turn: { id: turnId, status: "completed" } });
  turnId = undefined;
}

readline.createInterface({ input: process.stdin }).on("line", (line) => {
  let msg;
  try {
    msg = JSON.parse(line);
  } catch {
    return;
  }

  // A response to one of OUR server requests (the approval above).
  if (msg.id !== undefined && msg.method === undefined && (msg.result !== undefined || msg.error !== undefined)) {
    if (msg.id === 9001) {
      const decision = msg.result?.decision ?? "decline";
      notify("item/completed", {
        threadId,
        turnId,
        item: { type: "agentMessage", id: "am", text: `approval:${decision}` },
      });
      notify("turn/completed", { threadId, turn: { id: turnId, status: "completed" } });
      turnId = undefined;
    }
    return;
  }

  const { id, method, params } = msg;
  switch (method) {
    case "initialize":
      emit({ id, result: { userAgent: "fake-codex/9.9.9", codexHome: "/tmp", platformFamily: "unix", platformOs: "linux" } });
      return;
    case "thread/start":
      threadId = randomUUID();
      emit({ id, result: { thread: { id: threadId, cwd: params?.cwd, status: "idle" }, model: params?.model ?? "fake-codex-model" } });
      return;
    case "thread/resume":
      threadId = params?.threadId ?? randomUUID();
      resumed = true;
      // A resumed thread remembers; that is the whole point of resuming.
      memory.push("REMEMBER RESUMED-MEMORY");
      emit({ id, result: { thread: { id: threadId, status: "idle" }, model: params?.model ?? "fake-codex-model" } });
      return;
    case "turn/start": {
      const text = (params?.input ?? []).map((i) => i.text ?? "").join(" ");
      const newTurn = randomUUID();
      turnId = newTurn;
      emit({ id, result: { turn: { id: newTurn, status: "running" } } });
      void runTurn(text, newTurn);
      return;
    }
    case "turn/steer": {
      if (params?.expectedTurnId !== turnId) {
        emit({ id, error: { code: -32000, message: "expectedTurnId does not match the active turn" } });
        return;
      }
      steerText = (params?.input ?? []).map((i) => i.text ?? "").join(" ");
      emit({ id, result: { turnId } });
      return;
    }
    case "turn/interrupt":
      interrupted = true;
      emit({ id, result: {} });
      return;
    default:
      if (id !== undefined) emit({ id, error: { code: -32601, message: `unknown method ${String(method)}` } });
  }
});

process.stdin.on("end", () => process.exit(0));
